controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    Human.y += -3
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    Human.y += -15
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    Human.setPosition(80, 60)
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    Human.x += -3
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    Human.x += 3
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    Human.y += 3
})
let Human: Sprite = null
scene.setBackgroundColor(1)
Human = sprites.create(img`
    ........................
    ......ffff..............
    ....fff22fff............
    ...fff2222fff...........
    ..fffeeeeeefff..........
    ..ffe222222eef..........
    ..fe2ffffff2ef..........
    ..ffffeeeeffff..........
    .ffefbf44fbfeff.........
    .fee41fddf14eef.........
    fdfeeddddd4eff..........
    fbffee444edd4e..........
    fbf4f2222edde...........
    fcf.f22cccee............
    .ff.f44cdc4f............
    ....fffddcff............
    .....fddcff.............
    ....cddc................
    ....cdc.................
    ....cc..................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
